
# Configuration for Label Actions - https://github.com/dessant/label-actions

# The `Config` label is added to issues
Config:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Add Comment
    comment: |
      Thank you for taking the time to report a problem with RefindPlus.
      The problem has been assessed as being configuration/setup related.

      Please consult available documentation and amend your setup as required.
      Documentation is provided in the `ReadMe` on the front page of this repository
      as well as in the sample `config.conf` file. Additionally, extensive documentation
      provided upstream can be consulted as this is largely also applicable to RefindPlus.

# The `Noted` label is added to issues
Noted:
  issues:
    # Add labels
    label:
      - 'Tagged'
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Add Comment
    comment: |
      Thank you for taking the time to report a problem with RefindPlus.
      The problem is noted and will be considered as required.

# The `Confirmed` label is added to issues
Confirmed:
  issues:
    # Add labels
    label:
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Accepted` label is added to issues
Accepted:
  issues:
    # Add labels
    label:
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Reopen issue and unlock thread
    reopen: true
    unlock: true

# The `Declined` label is added to PRs
Declined:
  prs:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Closure reason
    close-reason: 'not planned'

# The `Declined` label is removed from PRs
-Declined:
  prs:
    # Reopen PR and unlock thread
    reopen: true
    unlock: true

# The `Uncertain` label is added to issues
Uncertain:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Bug` label is added to issues
Bug:
  issues:
    # Add labels
    label:
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Cancelled` label is added to issues
Cancelled:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Add Comment
    comment: >
      This item has been cancelled by/for: @{issue-author}

# The `Discussion` label is added to issues
Discussion:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Enhancement'
      - 'Cannot-Replicate'

# The `Dismissed` label is added to issues
Dismissed:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Closure reason
    close-reason: 'not planned'
    # Lock thread
    lock: true

# The `Documentation` label is added to issues
Documentation:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Cannot-Replicate'

# The `Duplicate` label is added to issues
Duplicate:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true
    # Add Comment
    comment: >
      This item is a duplicate of one or more existing items

# The `Enhancement` label is added to issues
Enhancement:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Tagged` label is added to issues
Tagged:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Good-First-Issue` label is added to issues
Good-First-Issue:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Help-Wanted` label is added to issues
Help-Wanted:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Cancelled'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Incomplete` label is added to issues
Incomplete:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Duplicate'
      - 'Prorogued'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Invalid` label is added to issues
Invalid:
  issues:
    # Add labels
    label:
      - 'Tagged'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Upstream'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Known-Issue` label is added to issues
Known-Issue:
  issues:
    # Add labels
    label:
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Parked` label is added to issues
Parked:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Tagged'
      - 'Stale'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Upstream` label is added to issues
Upstream:
  issues:
    # Add labels
    label:
      - 'Confirmed'
      - 'Unresolved'
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Tagged'
      - 'Stale'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Queries` label is added to issues
Queries:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Reopen issue and unlock thread
    reopen: true
    unlock: true

# The `Resolved` label is added to issues
Resolved:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Config'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Resolved` label is removed from issues
#-Resolved:
#   issues:
#     # Add labels
#     label:
#       - 'Unresolved'
#    # Reopen issue and unlock thread
#    reopen: true
#    unlock: true

# The `Stale` label is added to issues
Stale:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Prorogued'
      - 'Duplicate'

# The `Unclear` label is added to issues
Unclear:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Noted'
      - 'Config'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Not-Planned` label is added to issues
Not-Planned:
  issues:
    # Add labels
    label:
      - 'Tagged'
    # Remove labels
    unlabel:
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Not-Planned` label is removed from issues
-Not-Planned:
  issues:
    # Remove labels
    unlabel:
      - 'Tagged'
    # Reopen issue and unlock thread
    reopen: true
    unlock: true

# The `Cannot-Replicate` label is added to issues
Cannot-Replicate:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
    # Close thread
    close: true

# The `Cannot-Replicate` label is removed from issues
-Cannot-Replicate:
  issues:
    # Reopen issue and unlock thread
    reopen: true
    unlock: true

# The `Prorogued` label is added to issues
Prorogued:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Prorogued` label is removed from issues
-Prorogued:
  issues:
    # Reopen issue and unlock thread
    reopen: true
    unlock: true

# The `Triage` label is added to issues
Triage:
  issues:
    # Remove labels
    unlabel:
      - 'Not-Planned'
      - 'Unresolved'
      - 'Uncertain'
      - 'Confirmed'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Bug'
      - 'Noted'
      - 'Config'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Dismissed'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Reopen issue and unlock thread
    reopen: true
    unlock: true
