name: Bug Report
description: Report a problem with RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a problem with RefindPlus.\
        Please use the [DISCUSSIONS FEATURE](https://github.com/RefindPlusRepo/RefindPlus/discussions?discussions_q=sort%3Adate_created) instead if you wish to ask a question, make a comment or similar.


        ---


        **Try the item below first if RefindPlus fails to display/boot Linux.**
        Especially if running Linux Kernel v6.17.4 or newer.
        - Use filesystem drivers from RefindPlus:- `v0.14.2.AE or Newer`.

        **NB:** Previous FS driver versions failed on finding voids in binaries.


        ---


        **Try the item below first if RefindPlus fails to display but responds to key inputs on Apple Macs.**
        Especially if running 5k monitors on Pre-2020 units as the firmware restricts third-party loaders.
        - Run RefindPlus with these config settings active:- `disable_set_consolegop` and/or `disable_set_applefb`.

        **NB:** Firmware enforced resolution limits on third-party loaders may prevent 5k resolution display.


        ---


        **Try the steps below first if RefindPlus hangs on UEFI-PC [especially with Hewlett Parkard (HP) firmware]:**
        1. Run RefindPlus with the `ransom_drives` config setting active and `disable_rescan_dxe` inactive.
        2. Run RefindPlus with `disable_rescan_dxe` active and `ransom_drives` inactive if that fails.
        3. Run RefindPlus with both `ransom_drives` and `disable_rescan_dxe` active if that fails.

        **NB:** A hang is manifested by an unresponsive, partially / not-loaded, RefindPlus screen.


        ---
        <br><br>
        <h1 align="center">BUG REPORT DETAILS</h1>

  - type: dropdown
    id: issue-screened
    attributes:
      label: Issue Screened
      description: |
          Confirm the items above have been read and applied as required.
      options:
        - 'SUGGESTED_TESTS_EXECUTED or no_applicable_item'
        - 'SUGGESTED_TESTS_IGNORED despite applicable_item'
      default: 1
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: RefindPlus Version
      description: Which version of RefindPlus is affected?
      options:
        - 'Official v0.14.2.AE Release'
        - 'Official Older Released Version'
        - 'Official Pre-Release Code Build'
        - 'Unofficially Modified Code Build'
      default: 3
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Device Type
      description: Which device type?
      multiple: true
      options:
        - 'UEFI PC'
        - 'Apple Mac'
        - 'Other Device'
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: |
        Please provide a clear and concise description of the problem.
      placeholder: |
        Additionally, outline how to reproduce the problem.
    validations:
      required: true

  - type: dropdown
    id: problem-point
    attributes:
      label: Problem Point
      description: Where does the problem manifest itself?
      options:
        - 'Before RefindPlus Screen is Visible'
        - 'RefindPlus Screen Shows but Hangs'
        - 'Before Starting a Loader or Tool'
        - 'While Starting a Loader or Tool'
        - 'After Starting a Loader or Tool'
        - 'Another Point / Not Applicable'
        - 'No_Idea and/or Forgotten_Details'
      default: 6
    validations:
      required: true

  - type: dropdown
    id: os-type
    attributes:
      label: Affected Item(s)
      description: What aspect is affected?
      multiple: true
      options:
        - 'One/More Tools (2nd Row Items)'
        - 'All OS Loaders (1st Row Items)'
        - 'Mac OS Loader'
        - 'Win OS Loader'
        - 'Lin OS Loader'
        - 'SDBoot Loader'
        - 'The GRUB Loader'
        - 'OpenCore Loader'
        - 'Clover Loader'
        - 'Other Loader'
        - 'Other Item'
        - 'All Items'
    validations:
      required: true

  - type: textarea
    id: log-file
    attributes:
      label: Debug Log
      description: |
        Please run the RefindPlus 'DBG' efi and add debug logs.\
        Do attach the log files and _DO NOT_ paste their contents.\
        Attach log files by dragging/dropping on the field below.\
        Output log files are stored in the ESP holding RefindPlus.
      placeholder: |
        Reports that do not need log files are typically best as Discussions.
        Reports without log files will be automatically closed in most cases.
    validations:
      required: true

  - type: dropdown
    id: vet-debug
    attributes:
      label: Log Requirement
      description: |
          Debug logs are almost always required and produced by running the 'DBG' efi.\
          Confirm log files are provided or that you are certain this is not required.
      options:
        - 'DEBUG_LOGS_ARE_PROVIDED or omission_clearly_justified'
        - 'DEBUG_LOGS_NOT_PROVIDED - disregarding_guidance_given'
      default: 1
    validations:
      required: true

  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Additional details that may further make the problem clearer.
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also add screenshots to shed more light on the issue.
        Screenshot files can be created from RefindPlus with Key F10.
        Screenshot files will be saved in the ESP holding RefindPlus.
