name: Bug Report
description: Report a problem with RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a problem with RefindPlus.\
        Please use the [DISCUSSIONS FEATURE](https://github.com/RefindPlusRepo/RefindPlus/discussions/categories/general) instead if you wish to ask a question, make a comment or similar.


        ---


        Try the item below on Apple Macs first if RefindPlus fails to display but responds to key inputs.
        Especially if running 5k monitors on Pre-2020 units as the firmware restricts third-party loaders.
        - Run RefindPlus with these config settings active:- `disable_set_consolegop` and `disable_set_applefb`.

        Firmware enforced resolution limits on third-party loaders may prevent 5k resolution dsiplay.


        ---


        Try the steps below first if RefindPlus hangs on UEFI-PC [Especially with Hewlett Parkard (HP) units]:
        1. Run RefindPlus with the `ransom_drives` config setting active and `disable_rescan_dxe` inactive.
        2. Run RefindPlus with `disable_rescan_dxe` active and `ransom_drives` inactive if that fails.
        3. Run RefindPlus with both `ransom_drives` and `disable_rescan_dxe` active if that fails.

        NB: A hang is typically manifested by a failure to fully load the RefindPlus screen.


        ---


  - type: dropdown
    id: version
    attributes:
      label: RefindPlus Version
      description: Which version of RefindPlus is affected?
      options:
        - 'v0.14.2.AB Release'
        - 'Older Released Version'
        - 'Pre-Release Code Build'
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Device Type
      description: You can make more than one selection
      multiple: true
      options:
        - 'UEFI PC'
        - 'Apple Mac'
        - 'Other Device'
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: |
        Please provide a clear and concise description of the problem.
      placeholder: |
        Additionally, outline how to reproduce the problem.
    validations:
      required: true
  - type: dropdown
    id: problem-point
    attributes:
      label: Problem Point
      description: Where does the problem manifest itself?
      options:
        - 'Before RefindPlus Screen is Visible'
        - 'RefindPlus Screen Shows but Hangs'
        - 'Before Starting a Loader or Tool'
        - 'While Starting a Loader or Tool'
        - 'After Starting a Loader or Tool'
        - 'Another Point or Not Applicable'
    validations:
      required: true
  - type: dropdown
    id: os-type
    attributes:
      label: Affected Items
      description: You can make more than one selection
      multiple: true
      options:
        - 'One/More Tools (2nd Row Items)'
        - 'All OS Loaders (1st Row Items)'
        - 'Mac OS Loader'
        - 'Win OS Loader'
        - 'Lin OS Loader'
        - 'OpenCore Loader'
        - 'Clover Loader'
        - 'Other Loader'
        - 'Other Item'
        - 'All Items'
    validations:
      required: true
  - type: textarea
    id: log-file
    attributes:
      label: Debug Log
      description: |
        Please run the RefindPlus 'DBG' efi and add debug logs.\
        Please attach log files and _DO NOT_ paste their contents.\
        Attach log files by dragging/dropping on the field below.
      placeholder: |
        Reports that do not need log files are typically best as Discussions.
        Reports without log files will be automatically closed in most cases.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Additional details that may further make the problem clear.
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also add screenshots to shed more light on the issue.
        Screenshot files can be saved by RefindPlus with the F10 key.
