name: Bug Report
description: Report a problem with RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a problem with RefindPlus.
        Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature instead if you only wish to ask a question or make a comment.
  - type: dropdown
    id: version
    attributes:
      label: RefindPlus Version
      description: Which version of RefindPlus is affected?
      options:
        - 'v0.14.0.AC Release'
        - 'Older Released Version'
        - 'Pre-Release Code Build'
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Device Type
      description: You can make more than one selection
      multiple: true
      options:
        - 'UEFI PC'
        - 'Apple Mac'
        - 'Chromebook'
        - 'Other Device'
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: |
        Please provide a clear and concise description of the problem.
      placeholder: |
        Additionally, outline how to reproduce the problem.
    validations:
      required: true
  - type: dropdown
    id: problem-point
    attributes:
      label: Problem Point
      description: Where does the problem manifest itself?
      options:
        - 'RefindPlus fails to load'
        - 'Before starting a loader or tool'
        - 'While starting a loader or tool'
        - 'After starting a loader or tool'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    id: os-type
    attributes:
      label: Affected Items
      description: You can make more than one selection
      multiple: true
      options:
        - 'One or More Tools (Second Row Items)'
        - 'All OS Loaders (First Row Items)'
        - 'Mac OS Loader'
        - 'Win OS Loader'
        - 'Lin OS Loader'
        - 'OpenCore Loader'
        - 'Clover Loader'
        - 'Other Loader'
        - 'Other Item'
    validations:
      required: true
  - type: textarea
    id: log-file
    attributes:
      label: Debug Log
      description: |
        Please run the RefindPlus 'DBG' efi and add debug logs.
        Kindly attach logs and do not paste the contents directly.
        You can attach logs by dragging/dropping on the field below.
      placeholder: |
        Reports not requiring log files are typically best under Discussions.
        Reports without log files will be automatically closed in most cases.
        Debug logs at Log Level '0' are usually preferred over higher levels.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Additional details that may provide clarity on the problem.
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also add screenshots to aid understanding the problem.
        Screenshots can be saved by pressing the F10 key in RefindPlus.
