name: Bug Report
description: Report a Problem with RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a problem with RefindPlus.
        Please use the [DISCUSSIONS OPTION](https://github.com/dakanji/RefindPlus/discussions) instead if you wish to ask a question, make a comment or similar.

        NB: Before continuing, try running RefindPlus with the 'ransom_drives' configuration option set if the problem is that RefindPlus hangs on UEFI-PC with HP firmware.
  - type: dropdown
    id: version
    attributes:
      label: RefindPlus Version
      description: Which version of RefindPlus is affected?
      options:
        - 'v0.14.2.AA Release'
        - 'Older Released Version'
        - 'Pre-Release Code Build'
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Device Type
      description: You can make more than one selection
      multiple: true
      options:
        - 'UEFI PC'
        - 'Apple Mac'
        - 'Chromebook'
        - 'Other Device'
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: |
        Please provide a clear and concise description of the problem.
      placeholder: |
        Additionally, outline how to reproduce the problem.
    validations:
      required: true
  - type: dropdown
    id: problem-point
    attributes:
      label: Problem Point
      description: Where does the problem manifest itself?
      options:
        - 'RefindPlus crashes/hangs on start'
        - 'Before starting a loader or tool'
        - 'While starting a loader or tool'
        - 'After starting a loader or tool'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    id: os-type
    attributes:
      label: Affected Items
      description: You can make more than one selection
      multiple: true
      options:
        - 'One/More Tools (2nd Row Items)'
        - 'All OS Loaders (1st Row Items)'
        - 'Mac OS Loader'
        - 'Win OS Loader'
        - 'Lin OS Loader'
        - 'OpenCore Loader'
        - 'Clover Loader'
        - 'Other Loader'
        - 'Other Item'
        - 'All Items'
    validations:
      required: true
  - type: textarea
    id: log-file
    attributes:
      label: Debug Log
      description: |
        Please run the RefindPlus 'DBG' efi and add debug logs.
        Please attach log files and do not paste their contents.
        Attach log files by dragging/dropping on the field below.
      placeholder: |
        Reports that do not need log files are typically best as Discussions.
        Reports without log files will be automatically closed in most cases.
        Debug logs at Log Level '0' are usually preferred over higher levels.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Additional details that may provide clarity on the problem.
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also use screenshots to shed some light on the problem.
        Screenshots can be saved in RefindPlus by pressing the F10 key.
