name: Feature Request
description: Suggest improvements to RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest improvements to RefindPlus.
        If you actually only wish to ask a question or make a comment, please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) instead.
  - type: textarea
    id: suggested-feature
    attributes:
      label: Suggested Feature
      description: |
        Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: background-information
    attributes:
      label: Background Information
      description: |
        Add information about any alternative solutions or features you have considered.
        If your feature request related to a specific problem, please provide a clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: Add any additional context that may facilitate understanding and implementing the feature
