name: Feature Request
description: Suggest improvements to RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest improvements to RefindPlus.
        Please use the [DISCUSSIONS OPTION](https://github.com/dakanji/RefindPlus/discussions) instead if you wish to ask a question, make a comment or similar.
  - type: textarea
    id: suggested-feature
    attributes:
      label: Suggested Feature
      description: |
        Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: background-information
    attributes:
      label: Background Information
      description: |
        Add information about any alternative solutions/features considered.
        If the request is related to a specific problem, please provide a clear and concise description of such.
      placeholder: |
        Items for which this section is not applicable are typically best as Discussions.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Add any additional context that may facilitate understanding and implementing the feature
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also use screenshots to illustrate the suggested item.
        Screenshots can be saved in RefindPlus by pressing the F10 key.
