name: Feature Request
description: Suggest improvements to RefindPlus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest improvements to RefindPlus.
        Please [USE THE DISCUSSIONS OPTION INSTEAD](https://github.com/dakanji/RefindPlus/discussions) if you wish to ask a question, make a comment or request support.
  - type: textarea
    id: suggested-feature
    attributes:
      label: Suggested Feature
      description: |
        Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: background-information
    attributes:
      label: Background Information
      description: |
        Add information about any alternative solutions or features you have considered.
        If your feature request related to a specific problem, please provide a clear and concise description of the problem.
      placeholder: |
        Items for which this section is not applicable are typically best under Discussions.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Context
      description: |
        Add any additional context that may facilitate understanding and implementing the feature
      placeholder: |
        You can attach files by dragging/dropping them on this field.
        You can also add screenshots to aid understanding the problem.
        Screenshots can be saved by pressing the F10 key in RefindPlus.
