name: Build Artefacts

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Required Build Type(s)'
        type: choice
        options:
        - 'REL Only'
        - 'DBG Only'
        - 'NPT Only'
        - 'REL and DBG'
        - 'REL, DBG, NPT'
        default: 'REL and DBG'
      sign_output:
        description: 'Sign Binaries for Secure Boot?'
        type: choice
        options:
        - 'NO'
        - 'YES'
        default: 'NO'
      commit_id:
        description: 'Commit ID (Blank == GOPFix-Latest)'
        type: string
        required: false

jobs:
  make-binaries:
    name: Make Binaries
    runs-on: macos-26-intel

    steps:
      - name: List/Set Misc
        env:
          SET_REPO: ${{ github.repository }}
          SET_COMMIT_ID: ${{ github.event.inputs.commit_id }}
          SET_BUILD_TYPE: ${{ github.event.inputs.build_type }}
          SET_SIGN_OUTPUT: ${{ github.event.inputs.sign_output }}
        shell: bash
        run: |
          # List Misc Inputs
          echo "REPO       : '${SET_REPO}'"
          echo "ENV_REPO=${SET_REPO}" >> "${GITHUB_ENV}"

          USE_COMMIT_ID="${SET_COMMIT_ID:-GOPFix-Latest}"
          echo "COMMIT_ID  : '${USE_COMMIT_ID}'"
          echo "ENV_COMMIT_ID=${USE_COMMIT_ID}" >> "${GITHUB_ENV}"

          echo "BUILD_TYPE : '${SET_BUILD_TYPE}'"
          echo "ENV_BUILD_TYPE=${SET_BUILD_TYPE}" >> "${GITHUB_ENV}"

          echo "SECURE_BOOT: '${SET_SIGN_OUTPUT}'"

          # Set Misc Paths
          USE_BASE="${HOME}/Documents/RefindPlus"
          echo "ENV_BASE_DIR=${USE_BASE}" >> "${GITHUB_ENV}"
          echo "ENV_EDK2_DIR=${USE_BASE}/edk2" >> "${GITHUB_ENV}"
          echo "ENV_WORK_DIR=${USE_BASE}/Working" >> "${GITHUB_ENV}"

      - name: Get Repositories
        shell: bash
        run: |
          # Create Directories
          mkdir -p "${ENV_BASE_DIR}" || exit 1
          cd "${ENV_BASE_DIR}" || exit 1

          # Clone Refindplus Repo: Use Treeless Clone
          # Has History (for '--contains' if used)
          # REF: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone
          git clone --filter=tree:0 "https://github.com/${ENV_REPO}.git" Working || exit 1

          # Clone EDK2 Repo: Use Shallow Clone
          # Just a Build Dependency ... Minimal 'depth 1' Enough
          # REF: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone
          git clone --depth 1 "https://github.com/RefindPlusRepo/RefindPlusUDK.git" edk2 || exit 1

      - name: Determine Target Branch
        shell: bash
        run: |
          # Set Target Branch/Commit
          cd "${ENV_WORK_DIR}" || exit 1
          if [[ "${ENV_COMMIT_ID}" == 'GOPFix-Latest' ]] ; then
            echo "Blank Commit ID Input ... Use Defaults"
            BRANCH=GOPFix
          else
            echo "Find User Defined Branch via Commit ID"
            # Validate Input 'Commit ID'
            if [[ ! "${ENV_COMMIT_ID}" =~ ^[a-fA-F0-9]{7,40}$ ]]; then
              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
              echo '' >> "${GITHUB_STEP_SUMMARY}"

              echo "Error: Invalid Commit ID Format: '${ENV_COMMIT_ID}'"
              echo "       Must be Valid Git SHA (7-40 Hex Chars)"
              echo "       Exiting Now"
              exit 1
            fi

            # Fetch valid remote branches
            git fetch origin --prune || exit 1

            # Get Candidate Branches
            BranchList=$(git branch -r --contains "${ENV_COMMIT_ID}" | grep 'origin/' | sed 's|origin/||')
            if [[ -z "${BranchList}" ]]; then
              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
              echo '' >> "${GITHUB_STEP_SUMMARY}"

              echo "Error: Not Located on Any Branch: '${ENV_COMMIT_ID}'"
              echo "       Exiting Now"
              exit 1
            fi

            # Use Target Branch Commit
            BRANCH=$(printf "%s\n" "${BranchList}" | head -n 1 | tr -d '[:space:]')
            if ! git show-ref --verify --quiet "refs/remotes/origin/${BRANCH}"; then
              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
              echo '' >> "${GITHUB_STEP_SUMMARY}"

              echo "Error: Remote Branch Not Found: '${BRANCH}'"
              echo "       Paranoia Check Failed!"
              echo "       Exiting Now"
              exit 1
            fi

            # Set Target Branch to Commit ID
            git checkout "${BRANCH}" || exit 1
            git reset --hard "${ENV_COMMIT_ID}" || exit 1
          fi

          echo "BRANCH=${BRANCH}" >> "${GITHUB_ENV}"
          echo "Branch     : '${BRANCH}'"

          printf "Commit     : '%s'\nTitle      : '%s'\n" \
            "$(git rev-parse --short HEAD)" \
            "$(git log -1 --pretty=%B | sed 's/%/%%/g')"

          printf "Author     : '%s'\nDate       : '%s'\n" \
            "$(git log -1 --pretty='%an <%ae>')" \
            "$(git log -1 --pretty='%ad' --date=iso-strict)"

      - name: Apply Misc Prep
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        shell: bash
        run: |
          # Set Build Type(s)
          case "${ENV_BUILD_TYPE}" in
            "REL and DBG") BUILD_FLAG="TWO" ;;
            "REL Only")    BUILD_FLAG="REL" ;;
            "DBG Only")    BUILD_FLAG="DBG" ;;
            "NPT Only")    BUILD_FLAG="NPT" ;;
            *)             BUILD_FLAG="ALL" ;;
          esac

          echo "BUILD_FLAG=${BUILD_FLAG}" >> "${GITHUB_ENV}"
          echo "Build Flag : '${BUILD_FLAG}'"

          # Set Type Flag
          FlagFind=0
          ADD_TAG="${ENV_WORK_DIR}/Main/main.c"
          if [[ -f "${ADD_TAG}" ]]; then
            FlagFind=1
          else
            ADD_TAG="${ENV_WORK_DIR}/BootMaster/main.c"
            if [[ -f "${ADD_TAG}" ]]; then
              FlagFind=1
            fi
          fi

          if (( FlagFind )) ; then
            /usr/bin/perl -i -p -e 's~\(Local\)~(Outer)~' "${ADD_TAG}" || {
              echo "[NOTE] Tag Replacement Failed: '${ADD_TAG}'"
            }
          fi

          # Install Additional Build Tools
          PKGS="nasm acpica ocmtoc"
          brew install ${PKGS} || (
            brew update && brew install ${PKGS}
          )

          # Install Final Python 2 Version
          PYTHON_VER='2.7.18'
          PYTHON_PKG="python-${PYTHON_VER}-macosx10.9.pkg"
          EXPECTED_HASH='ce98eeb7bdf806685adc265ec1444463'

          PYTHON2_INSTALLER="${ENV_EDK2_DIR}/Conf/Blobs/${PYTHON_PKG}"
          if [[ -f "${PYTHON2_INSTALLER}" ]]; then
            cp -f "${PYTHON2_INSTALLER}" . || true
          fi

          if [[ -f "${PYTHON_PKG}" ]]; then
            printf "\nUsing Bundled Python %s\n" "${PYTHON_VER}"
            printf "Verify Python %s File\n" "${PYTHON_VER}"
            OBTAINED_HASH=$(md5 -q "${PYTHON_PKG}")
            if [[ "${OBTAINED_HASH}" != "${EXPECTED_HASH}" ]]; then
              echo "ERROR: Python Bundle Checksum Check Failure"
              echo "       Expected: ${EXPECTED_HASH}"
              echo "       Obtained: ${OBTAINED_HASH}"

              rm -f "${PYTHON_PKG}"
              printf "\n\nFetch From Project Page Instead"
            fi
          fi

          if [[ ! -f "${PYTHON_PKG}" ]]; then
            PYTHON_URL="https://www.python.org/ftp/python/${PYTHON_VER}/${PYTHON_PKG}"
            printf "\nDownloading Python %s\n" "${PYTHON_VER}"
            curl --retry 3 --fail -O "${PYTHON_URL}" || {
              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed Step:- 'Make Binaries ... Apply Misc Prep'" >> "${GITHUB_STEP_SUMMARY}"
              echo '' >> "${GITHUB_STEP_SUMMARY}"

              printf "\nERROR: Python %s Download Failed\n" "${PYTHON_VER}"
              exit 1
            }

            printf "Verify Python %s Download\n" "${PYTHON_VER}"
            OBTAINED_HASH=$(md5 -q "${PYTHON_PKG}")
            if [[ "${OBTAINED_HASH}" != "${EXPECTED_HASH}" ]]; then
              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
              echo "> Failed Step:- 'Make Binaries ... Apply Misc Prep'" >> "${GITHUB_STEP_SUMMARY}"
              echo '' >> "${GITHUB_STEP_SUMMARY}"

              echo "ERROR: Python Download Checksum Check Failure"
              echo "       Expected: ${EXPECTED_HASH}"
              echo "       Obtained: ${OBTAINED_HASH}"
              echo "       Exiting Now"
              exit 1
            fi
          fi

          printf "Verified ... Installing Python %s\n" "${PYTHON_VER}"
          sudo installer -pkg "${PYTHON_PKG}" -target /

      - name: Run Main Script
        env:
          TERM: xterm
        shell: bash
        run: |
          # Main Build Script
          export IS_REMOTE='1'
          cd "${ENV_BASE_DIR}/edk2/000-BuildScript" || exit 1
          chmod +x RefindPlusBuilder.sh
          ./RefindPlusBuilder.sh --build-type="${BUILD_FLAG}"
          unset IS_REMOTE


        ###
        # If signing is active, prefix with 'NOT_SIGNED---' for the
        # signing job to handle the final outputs without collision
        ###
      - name: Upload Artefact (REL)
        if: success() && contains(github.event.inputs.build_type, 'REL')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_REL' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_REL' }}"
          path: |
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5/x64/*.efi
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5/x64/*.txt

      - name: Upload Artefact (DBG)
        if: success() && contains(github.event.inputs.build_type, 'DBG')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_DBG' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_DBG' }}"
          path: |
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/DEBUG_XCODE5/x64/*.efi
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/DEBUG_XCODE5/x64/*.txt

      - name: Upload Artefact (NPT)
        if: success() && contains(github.event.inputs.build_type, 'NPT')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_NPT' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_NPT' }}"
          path: |
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/NOOPT_XCODE5/x64/*.efi
              ~/Documents/RefindPlus/edk2/Build/RefindPlus/NOOPT_XCODE5/x64/*.txt


      ###
      # Advice on recommended action on file names
      # Only display here if not signing artefacts
      # Otherwise, display after signing artefacts
      ###
      - name: Build Notice
        if: ${{ github.event.inputs.sign_output == 'NO' }}
        shell: bash
        run: |
          # Wrap Up Notice
          echo "# RefindPlus ... A Boot Manager for Mac and PC" > "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "Copyright 2020-2026 Dayo Akanji" >> "${GITHUB_STEP_SUMMARY}"
          echo "sf.net/u/dakanji/profile" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright 2012-2024 Roderick W. Smith" >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright 2006-2010 Christoph Pfisterer" >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright The Intel Corporation & Others" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "RefindPlus is free software. You can modify it and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
          echo "under the terms of the GNU General Public License as published by the" >> "${GITHUB_STEP_SUMMARY}"
          echo "Free Software Foundation. Either version 3 of the License (GNU GPLv3)" >> "${GITHUB_STEP_SUMMARY}"
          echo "or at your option, any later version of the License." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "RefindPlus is distributed in the hope that it will be useful," >> "${GITHUB_STEP_SUMMARY}"
          echo "but WITHOUT ANY WARRANTY; without even the implied warranty" >> "${GITHUB_STEP_SUMMARY}"
          echo "of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE." >> "${GITHUB_STEP_SUMMARY}"
          echo "See the GNU General Public License for more details." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "A copy of GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
          echo "If missing, you can access copies at the links below:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/LICENSE.txt" >> "${GITHUB_STEP_SUMMARY}"
          echo "- gnu.org/licenses/gpl-3.0.en.html" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"

          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
          echo "---" >> "${GITHUB_STEP_SUMMARY}"
          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

          echo "> [!NOTE]" >> "${GITHUB_STEP_SUMMARY}"
          echo "> Output files have the form: \`[METADATA]---[FILENAME].efi\`." >> "${GITHUB_STEP_SUMMARY}"
          echo "> It is anticipated the metadata will be discarded before use." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"

          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
          echo "---" >> "${GITHUB_STEP_SUMMARY}"
          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

          echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
          echo "> Output files with \`BLB_xx_???\` in their filename metadata ARE NOT part of RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs are bundled with RefindPlusUDK and provided as convenience items." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs WERE NOT built on RefindPlus code and were developed by others." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs are separately licensed by their actual respective developers." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_shell.efi**: OpenCore Project (OpenShell) ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_CleanNvram.efi**: OpenCore Project ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_memtest86p.efi**: MemTest Project ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_gdisk.efi**: Roderick Smith ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_ipxe.efi**: IPXE Project ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"

          echo "<br>" >> "${GITHUB_STEP_SUMMARY}"
          echo ". . ." >> "${GITHUB_STEP_SUMMARY}"


  sign-binaries:
    name: Sign Binaries
    needs: make-binaries
    if: ${{ github.event.inputs.sign_output == 'YES' }}
    runs-on: ubuntu-latest
    steps:
      - name: Prep Steps
        shell: bash
        run: |
          # Prepare Summmary
          echo "# RefindPlus ... A Boot Manager for Mac and PC" > "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "Copyright 2020-2026 Dayo Akanji" >> "${GITHUB_STEP_SUMMARY}"
          echo "sf.net/u/dakanji/profile" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright 2012-2024 Roderick W. Smith" >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright 2006-2010 Christoph Pfisterer" >> "${GITHUB_STEP_SUMMARY}"
          echo "Portions Copyright The Intel Corporation & Others" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "RefindPlus is free software. You can modify it and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
          echo "under the terms of the GNU General Public License as published by the" >> "${GITHUB_STEP_SUMMARY}"
          echo "Free Software Foundation. Either version 3 of the License (GNU GPLv3)" >> "${GITHUB_STEP_SUMMARY}"
          echo "or at your option, any later version of the License." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "RefindPlus is distributed in the hope that it will be useful," >> "${GITHUB_STEP_SUMMARY}"
          echo "but WITHOUT ANY WARRANTY; without even the implied warranty" >> "${GITHUB_STEP_SUMMARY}"
          echo "of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE." >> "${GITHUB_STEP_SUMMARY}"
          echo "See the GNU General Public License for more details." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "A copy of GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
          echo "If missing, you can access copies at the links below:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/LICENSE.txt" >> "${GITHUB_STEP_SUMMARY}"
          echo "- gnu.org/licenses/gpl-3.0.en.html" >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"

      - name: Validate Repository Secrets
        shell: bash
        env:
          INPUT_KEY: ${{ secrets.SIG_RP_KEY }}
          INPUT_CRT: ${{ secrets.SIG_RP_CRT }}
          INPUT_CER: ${{ secrets.SIG_RP_CER }}
        run: |
          # Vet Repository Secrets Setup (If Detected)
          [[ -z "${INPUT_KEY}" && (-n "${INPUT_CRT}" || -n "${INPUT_CER}") ]] && NO_KEY=1 || NO_KEY=0
          [[ -n "${INPUT_KEY}" &&  -z "${INPUT_CRT}" ]]                       && NO_CRT=1 || NO_CRT=0
          [[ -n "${INPUT_CER}" &&  -z "${INPUT_CRT}" && "${NO_CRT}" == "0" ]] && NO_CRT=1 || true

          if (( NO_KEY || NO_CRT )); then
            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
            echo "---" >> "${GITHUB_STEP_SUMMARY}"
            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

            echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
            echo "> The Artefacts HAVE NOT been Signed." >> "${GITHUB_STEP_SUMMARY}"
            echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
            echo "> Failed Step:- 'Sign Binaries ... Validate Repository Secrets'" >> "${GITHUB_STEP_SUMMARY}"
            echo '' >> "${GITHUB_STEP_SUMMARY}"

            echo "ERROR: Invalid Repository Secrets Setup for Secure Boot Signing"

            (( NO_KEY )) && echo "       The required 'SIG_RP_KEY' repository secret is missing" || true
            (( NO_CRT )) && echo "       The required 'SIG_RP_CRT' repository secret is missing" || true

            echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
            echo "       Exiting Now"
            exit 1
          fi

      - name: Fetch Interim Artefact (REL)
        if: contains(github.event.inputs.build_type, 'REL')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_REL
          path: Unsigned_REL

      - name: Fetch Interim Artefact (DBG)
        if: contains(github.event.inputs.build_type, 'DBG')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_DBG
          path: Unsigned_DBG

      - name: Fetch Interim Artefact (NPT)
        if: contains(github.event.inputs.build_type, 'NPT')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_NPT
          path: Unsigned_NPT

      - name: Prepare to Sign Binaries
        shell: bash
        env:
          ENV_USER_KEY: ${{ secrets.SIG_RP_KEY }}
          ENV_USER_CRT: ${{ secrets.SIG_RP_CRT }}
          ENV_USER_CER: ${{ secrets.SIG_RP_CER }}
        run: |
          # Handle Certificate and Private Key
          Certs="Artefact_Certs"
          mkdir -p "${Certs}"
          NOW=$(date +%y%m%d%H%M%S)
          CERT_PATH="${Certs}/build_cert_${NOW}"

          if [[ -n "${ENV_USER_KEY}" ]]; then
            echo "Cert/Key: Fetch User-Provided"
            echo "${ENV_USER_KEY}" > "${CERT_PATH}.key"

            if [[ -n "${ENV_USER_CRT}" ]]; then
              echo "${ENV_USER_CRT}" > "${CERT_PATH}.crt"
            fi
            if [[ -n "${ENV_USER_CER}" ]]; then
              echo "${ENV_USER_CER}" > "${CERT_PATH}.cer"
            fi
          fi

          OUR_CERT_KEY="${CERT_PATH}.key"
          OUR_CERT_CRT="${CERT_PATH}.crt"
          OUR_CERT_CER="${CERT_PATH}.cer"

          if [[ ! -f "${OUR_CERT_CRT}" ]]; then
            echo "Cert/Key: Generate Transient"
            openssl req -new -x509 -nodes \
              -newkey rsa:2048 \
              -keyout "${OUR_CERT_KEY}" \
              -out "${OUR_CERT_CRT}" \
              -days 3650 \
              -subj "/CN=RefindPlus Build Artefact ${NOW}/"

            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
            echo "---" >> "${GITHUB_STEP_SUMMARY}"
            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

            echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
            echo "> A one-off private key was used to sign the artefacts.  " >> "${GITHUB_STEP_SUMMARY}"
            echo "> This key was discarded as cannot be securely transferred.  " >> "${GITHUB_STEP_SUMMARY}"
            echo "> Hence, the certificate can only be used for this specific build.  " >> "${GITHUB_STEP_SUMMARY}"
            echo '' >> "${GITHUB_STEP_SUMMARY}"
            echo "See [RefindPlus Documentation](https://github.com/RefindPlusRepos/RefindPlus/blob/GOPFix/BUILDING.md) for how to supply reusable credentials." >> "${GITHUB_STEP_SUMMARY}"
          fi

          if [[ -f "${OUR_CERT_CRT}" && ! -f "${OUR_CERT_CER}" ]]; then
            # Create '.cer' From '.crt' For UEFI Enrolment
            openssl x509 \
              -in "${OUR_CERT_CRT}" \
              -out "${OUR_CERT_CER}" \
              -outform DER
          fi

          # Store Outputs for Subsequent Steps
          echo "FILE_KEY=${OUR_CERT_KEY}" >> $GITHUB_ENV
          echo "FILE_CRT=${OUR_CERT_CRT}" >> $GITHUB_ENV
          echo "FILE_CER=${OUR_CERT_CER}" >> $GITHUB_ENV
          echo "FLAG_NOW=${NOW}"          >> $GITHUB_ENV

      - name: Sign Requested Binaries
        env:
          ENV_TYPE: ${{ github.event.inputs.build_type }}
        shell: bash
        run: |
          # Sign Artefacts

          ###
          # Apply signature to specified item
          ###
          do_summary() {
            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
            echo "---" >> "${GITHUB_STEP_SUMMARY}"
            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

            echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
            echo "> The Artefacts HAVE NOT been Signed." >> "${GITHUB_STEP_SUMMARY}"
            echo "> See the failed step log for details." >> "${GITHUB_STEP_SUMMARY}"
            echo "> Failed Step:- 'Sign Binaries ... Sign Requested Binaries'" >> "${GITHUB_STEP_SUMMARY}"
            echo '' >> "${GITHUB_STEP_SUMMARY}"
          }

          ###
          # Apply signature to specified item
          ###
          sign_the_item() {
            local file_in="${1}"
            local file_out="${2}"

            echo "[SIGN] '${file_in}' >>---> as >>---> '${file_out}'"
            sbsign --key "${FILE_KEY}" \
                   --cert "${FILE_CRT}" \
                   --output "${file_out}" "${file_in}" || {
              do_summary ;

              echo "ERROR: Failed While Signing ${file_in}"
              echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
              echo "       Exiting Now"
              exit 1
            }
          }

          ###
          # Apply signature to set of artefacts
          ###
          sign_artefacts() {
            local target="${1}"

            local base=""
            local infile=""
            local outfile=""
            local sign_item=1
            local dir_in="Unsigned_${target}"

            local dir_out="${target}_signed_DIR"
            mkdir -p "${dir_out}"

            printf "\n\n"
            echo "===== Signing Target: ${target} ====="

            # Sign Main Binary
            printf 'Sign Main Binary...\n'
            name_tag="RefindPlus_${target}"
            base="APP_xx_000---x64_${name_tag}"
            infile="${dir_in}/${base}.efi"
            outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

            sign_item=1
            if [[ ! -f "${infile}" ]]; then
              base="UEFI_APP---x64_${name_tag}"
              infile="${dir_in}/${base}.efi"
              outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

              if [[ ! -f "${infile}" ]]; then
                do_summary ;

                echo "ERROR: Main Binary Not Found: 'x64_${name_tag}.efi'"
                echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                echo "       Exiting Now"
                exit 1
              fi
            fi
            (( sign_item )) && sign_the_item "${infile}" "${outfile}" || true

            # Sign Main Tool
            printf '\nSign Main Tool...\n'
            name_tag="gptsync"
            base="APP_xx_${target}---x64_${name_tag}"
            infile="${dir_in}/${base}.efi"
            outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

            sign_item=1
            if [[ ! -f "${infile}" ]]; then
              base="UEFI_APP---x64_${name_tag}"
              infile="${dir_in}/${base}.efi"
              outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

              if [[ ! -f "${infile}" ]]; then
                sign_item=0
                echo "[WARN] Not Found: 'x64_${name_tag}.efi' ... SKIPPED"
              fi
            fi
            (( sign_item )) && sign_the_item "${infile}" "${outfile}" || true

            # Sign Misc Blobs
            printf '\nSign Misc Blobs...\n'
            for name_tag in shell memtest86p gdisk CleanNvram ipxe; do
              base="BLB_xx_${target}---x64_${name_tag}"
              infile="${dir_in}/${base}.efi"
              outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

              sign_item=1
              if [[ ! -f "${infile}" ]]; then
                base="UEFI_APP---x64_${name_tag}_${target}"
                infile="${dir_in}/${base}.efi"
                outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

                if [[ ! -f "${infile}" ]]; then
                  sign_item=0
                  echo "[WARN] Not Found: 'x64_${name_tag}.efi' ... SKIPPED"
                fi
              fi
              (( sign_item )) && sign_the_item "${infile}" "${outfile}" || true
            done

            # Sign Filesystem Drivers
            printf '\nSign Filesystem Drivers...\n'
            for name_tag in btrfs ext2 ext4 hfs iso9660 ntfs reiserfs; do
              base="DRV_xx_${target}---x64_${name_tag}"
              infile="${dir_in}/${base}.efi"
              outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

              sign_item=1
              if [[ ! -f "${infile}" ]]; then
                base="DRIVER_${target}---x64_${name_tag}"
                infile="${dir_in}/${base}.efi"
                outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"

                if [[ ! -f "${infile}" ]]; then
                  sign_item=0
                  echo "[WARN] Not Found: 'x64_${name_tag}.efi' ... SKIPPED"
                fi
              fi
              (( sign_item )) && sign_the_item "${infile}" "${outfile}" || true
            done

            # Attach Licence Files
            printf '\nAttach Licensing...\n'
            for name_tag in INFO LICENSE; do
              base="000_xx_000---${name_tag}"
              infile="${dir_in}/${base}.txt"
              outfile="${dir_out}/${base}.txt"

              if [[ ! -f "${infile}" ]]; then
                echo "[WARN] Could not find '${infile}'"
              else
                cp -f "${infile}" "${outfile}" || true
                echo "[COPY] '${infile}' >>---> to >>---> '${outfile}'" || true
              fi
            done

            printf "\n"
            echo "= = = = Signed Target = = = ="
          }

          # Set Flag
          case "${ENV_TYPE}" in
            "REL and DBG") FLAG="TWO" ;;
            "REL Only")    FLAG="REL" ;;
            "DBG Only")    FLAG="DBG" ;;
            "NPT Only")    FLAG="NPT" ;;
            *)             FLAG="ALL" ;;
          esac

          # Sign Binaries
          [[ "${FLAG}" == "REL" || "${FLAG}" == "ALL" || "${FLAG}" == "TWO" ]] && sign_artefacts REL || true
          [[ "${FLAG}" == "DBG" || "${FLAG}" == "ALL" || "${FLAG}" == "TWO" ]] && sign_artefacts DBG || true
          [[ "${FLAG}" == "NPT" || "${FLAG}" == "ALL" ]]                       && sign_artefacts NPT || true


        ###
        # Handle interim artefacts, which are now deleted to leave
        # a final definititve set of artefacts with the same names
        # as produced when signing for secure boot is not required
        ###
      - name: Remove Interim Unsigned Artefacts
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_REPO: ${{ github.repository }}
          ENV_GHID: ${{ github.run_id }}
        shell: bash
        run: |
          echo "Remove Interim Unsigned Artefacts"
          got_artefacts=$(gh api "repos/${ENV_REPO}/actions/runs/${ENV_GHID}/artifacts" \
            --jq '.artifacts[] | select(.name | startswith("NOT_SIGNED---")) | "\(.id):\(.name)"')

          if [[ -z "${got_artefacts}" ]]; then
            echo "Interim Unsigned Artefacts Not Found"
            exit 0
          fi

          NotFirstPass=0
          NoStepSummary=1
          while IFS=":" read -r artifact_id artifact_name; do
            echo "Found: ${artifact_name} (${artifact_id})"
            CleanStrip=1
            (( NotFirstPass )) && sleep 2 || true
            gh api --method DELETE repos/"${ENV_REPO}"/actions/artifacts/"${artifact_id}" || CleanStrip=0

            if (( CleanStrip )); then
              echo "Removed Interim Artefact: ${artifact_name} (ID: ${artifact_id})"
              NotFirstPass=1
            else
              NotFirstPass=0
              echo "[WARN] Failed to Remove Interim Artefact: ${artifact_name} (ID: ${artifact_id})"
              if (( NoStepSummary )); then
                NoStepSummary=0

                echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
                echo "---" >> "${GITHUB_STEP_SUMMARY}"
                echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

                echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
                echo "> Failed to remove one or more interim unsigned artefacts" >> "${GITHUB_STEP_SUMMARY}"
              fi
            fi
          done <<< "${got_artefacts}"


        ###
        # Always include the certificate files along with the
        # signed binaries for users to enrol for Secure Boot
        ###
      - name: Upload Signed Binaries (REL)
        if: contains(github.event.inputs.build_type, 'REL')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_REL
          path: |
              ${{ env.FILE_CER }}
              ${{ env.FILE_CRT }}
              REL_signed_DIR/*.efi
              REL_signed_DIR/*.txt

      - name: Upload Signed Binaries (DBG)
        if: contains(github.event.inputs.build_type, 'DBG')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_DBG
          path: |
              ${{ env.FILE_CER }}
              ${{ env.FILE_CRT }}
              DBG_signed_DIR/*.efi
              DBG_signed_DIR/*.txt

      - name: Upload Signed Binaries (NPT)
        if: contains(github.event.inputs.build_type, 'NPT')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_NPT
          path: |
              ${{ env.FILE_CER }}
              ${{ env.FILE_CRT }}
              NPT_signed_DIR/*.efi
              NPT_signed_DIR/*.txt


      ###
      # Advice on recommended action on file names
      # Always displayed here if signing artefacts
      ###
      - name: Signature Notice
        if: always()
        shell: bash
        run: |
          # Wrap Up Notice
          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
          echo "---" >> "${GITHUB_STEP_SUMMARY}"
          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

          echo "> [!NOTE]" >> "${GITHUB_STEP_SUMMARY}"
          echo "> Output files have the form: \`[METADATA]---[FILENAME].efi\`." >> "${GITHUB_STEP_SUMMARY}"
          echo "> It is anticipated the metadata will be discarded before use." >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"

          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
          echo "---" >> "${GITHUB_STEP_SUMMARY}"
          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"

          echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
          echo "> Output files with \`BLB_xx_???\` in their filename metadata ARE NOT part of RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs are bundled with RefindPlusUDK and provided as convenience items." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs WERE NOT built on RefindPlus code and were developed by others." >> "${GITHUB_STEP_SUMMARY}"
          echo "> These binary blobs are separately licensed by their actual respective developers." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_shell.efi**: OpenCore Project (OpenShell) ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_CleanNvram.efi**: OpenCore Project ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_memtest86p.efi**: MemTest Project ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_gdisk.efi**: Roderick Smith ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
          echo "> \- **x64_ipxe.efi**: IPXE Project ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"

          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo "<br>" >> "${GITHUB_STEP_SUMMARY}"
          echo ". . ." >> "${GITHUB_STEP_SUMMARY}"
