name: Build Artefacts

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Required Build Type(s)'
        type: choice
        options:
        - 'REL Only'
        - 'DBG Only'
        - 'NPT Only'
        - 'REL and DBG'
        - 'REL, DBG and NPT'
        default: 'REL and DBG'
      commit_id:
        description: "Commit ID (Blank for GOPFix Latest)"
        type: string
        required: false

jobs:
  make-binaries:
    name: Make Binaries
    runs-on: macos-latest

    steps:
      - name: Get Repositories
        env:
          GET_REPO: ${{ github.repository }}
          GET_COMMIT_ID: ${{ github.event.inputs.commit_id }}
        shell: bash
        run: |
          mkdir ~/Documents/RefindPlus || exit 1
          cd ~/Documents/RefindPlus || exit 1

          # Clone RefindPlusUDK
          git clone https://github.com/RefindPlusRepo/RefindPlusUDK.git edk2

          # Clone RefindPlus
          git clone "https://github.com/${GET_REPO}.git" Working
          cd Working || exit 1

          # Find Target Branch
          if [ -z "${GET_COMMIT_ID}" ]; then
            # Use Default Branch
            BRANCH=GOPFix
          else
            # Get All Branches
            git fetch --all
            RemoteBranches=$(git branch -r | grep -v '\->')
            for RemoteName in "${RemoteBranches}"; do
              LocalName="${RemoteName#origin/}"
              git branch --track "${LocalName}" "${RemoteName}"

              # Redundant update below is delibrate
              git checkout "${LocalName}"
              git pull
            done

            # Get Candidate Branches
            BranchList=$(git branch -a --contains ${GET_COMMIT_ID} | grep -v '\->')
            if [ -z "${BranchList}" ]; then
              echo "Error: Commit ID not located on any branch!"
              exit 1
            fi

            # Use Target Branch Commit
            BRANCH=$(echo "${BranchList}" | head -n 1 | sed 's/origin\///' | sed 's/remotes\///')
            git checkout "${BRANCH}"
            git reset --hard "${GET_COMMIT_ID}"
          fi
          echo "BRANCH=${BRANCH}" >> "${GITHUB_ENV}"

      - name: Set Targets
        env:
          GET_BUILD_TYPE: ${{ github.event.inputs.build_type }}
        shell: bash
        run: |
          case "${GET_BUILD_TYPE}" in
            "REL and DBG") BUILD_TYPE="SOME" ;;
            "REL Only")    BUILD_TYPE="REL" ;;
            "DBG Only")    BUILD_TYPE="DBG" ;;
            "NPT Only")    BUILD_TYPE="NPT" ;;
            *)             BUILD_TYPE="ALL" ;;
          esac
          echo "BUILD_TYPE=${BUILD_TYPE}" >> "${GITHUB_ENV}"

      - name: Install Prerequisites
        shell: bash
        run: |
          # Install Additional Build Tools
          brew install nasm
          brew install acpica
          brew install ocmtoc

          # Install Final Python 2 Version
          curl -O https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg
          sudo installer -pkg python-2.7.18-macosx10.9.pkg -target /

      - name: Main Script
        env:
          TERM: xterm
        shell: bash
        run: |
          cd ~/Documents/RefindPlus/edk2/000-BuildScript || exit 1
          chmod +x RefindPlusBuilder.sh
          ./RefindPlusBuilder.sh "${BRANCH}" "${BUILD_TYPE}"

      - name: Upload Artefact (RELEASE)
        if: success() && contains(github.event.inputs.build_type, 'REL')
        uses: actions/upload-artifact@v4
        with:
          name: x64_RefindPlus-Artefacts_REL
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5/x64/*.efi

      - name: Upload Artefact (DEBUG)
        if: success() && contains(github.event.inputs.build_type, 'DBG')
        uses: actions/upload-artifact@v4
        with:
          name: x64_RefindPlus-Artefacts_DBG
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/DEBUG_XCODE5/x64/*.efi

      - name: Upload Artefact (NOOPT)
        if: success() && contains(github.event.inputs.build_type, 'NPT')
        uses: actions/upload-artifact@v4
        with:
          name: x64_RefindPlus-Artefacts_NPT
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/NOOPT_XCODE5/x64/*.efi
