name: 'Issue Helper Label Add'

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: Issue Action
        options:
        - 'Label - Add - Abandoned'
        - 'Label - Add - Cancelled'
        - 'Label - Add - Cannot-Replicate'
        - 'Label - Add - Incomplete - Issues'
        - 'Label - Add - Incomplete - Enhancement'
        - 'Label - Add - Invalid'
        - 'Label - Add - Triage'
        - 'Label - Add - Parked'
        - 'Label - Add - Prorogued'
        - 'Label - Add - Resolved'
        - 'Label - Add - Tagged'
        - 'Label - Add - Queries'
        - 'Label - Add - Upstream'
        - 'Label - Add - Not-Planned'
      item_id:
        description: 'Item ID'
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  label_add_abandoned:
    name: Label - Add - Abandoned
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Abandoned'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Abandoned'

  label_add_cannot-cancelled:
    name: Label - Add - Cancelled
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Cancelled'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Cancelled'

  label_add_cannot-replicate:
    name: Label - Add - Cannot-Replicate
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Cannot-Replicate'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Cannot-Replicate'

  label_add_incomplete_issue:
    name: Label - Add - Incomplete - Issues
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Incomplete - Issues'
    steps:

      - name: Label - Add - Incomplete - Issues - 1
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            Dear @${{ github.event.issue.user.login }},

            Thank you for taking the time to report a problem with RefindPlus.
            However, at least one required item is missing.
            This is typically debug log(s).

            Please kindly amend your post accordingly.

      - name: Label - Add - Incomplete - Issues - 2
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Incomplete'

      - name: Label - Add - Incomplete - Issues - 3
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage'

  label_add_incomplete_enhancement:
    name: Label - Add - Incomplete - Enhancement
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Incomplete - Enhancement'
    steps:

      - name: Label - Add - Incomplete - Enhancement - 1
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            Dear @${{ github.event.issue.user.login }},

            Thank you for taking the time to suggest improvements to RefindPlus.
            However, at least one required item is missing.
            This is typically useful background information.

            Please kindly amend your post accordingly.

      - name: Label - Add - Incomplete - Enhancement - 2
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Incomplete'

      - name: Label - Add - Incomplete - Enhancement - 3
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage'

  label_add_invalid:
    name: Label - Add - Invalid
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Invalid'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Invalid'

  label_add_pending:
    name: Label - Add - Triage
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Triage'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage'

  label_add_parked:
    name: Label - Add - Parked
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Parked'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Parked'

  label_add_prorogued:
    name: Label - Add - Prorogued
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Prorogued'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Prorogued'

  label_add_resolved:
    name: Label - Add - Resolved
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Resolved'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Resolved'

  label_add_tagged:
    name: Label - Add - Tagged
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Tagged'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Tagged'

  label_add_queries:
    name: Label - Add - Queries
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Queries'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Queries'

  label_add_upstream:
    name: Label - Add - Upstream
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Upstream'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Upstream'

  label_add_wontfix:
    name: Label - Add - Not-Planned
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Label - Add - Not-Planned'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Not-Planned'
