name: 'Issue Helper Change Title'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'Issue ID'
        type: number
        required: true
      new_title:
        description: 'New Issue Title'
        type: string
        required: true
      provenance_known:
        description: 'User RefindPlus Provenance Known?'
        type: choice
        options:
        - 'YES'
        - 'NO'
        default: 'YES'
      provenance_tag:
        description: 'Optional Tag if NO Above'
        type: string
        default: 'Exhibits Issues'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  issue_change_title:
    name: Issue - Change - Title
    runs-on: ubuntu-latest

    steps:
      # Generate App Token - https://github.com/actions/create-github-app-token
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Get/Save Issue Data - GitHub API
      - id: changetitle_01
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const issueNumber = context.payload.inputs.item_id;
            const { data } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            const isLocked = data.locked ? 'true' : 'false';
            const isClosed = data.state === 'closed' ? 'true' : 'false';

            // To use in the same job
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `isclosed=${isClosed}\n`);
            fs.appendFileSync(process.env.GITHUB_ENV, `islocked=${isLocked}\n`);

            // To use in other jobs ... For reference
            // Access with 'needs.<job>.outputs'
            // Must have 'changetitle_01' as a 'needs:' dependency
            //core.setOutput('isclosed', isClosed);
            //core.setOutput('islocked', isLocked);

      # Set NodeJS Up - https://github.com/actions/setup-node
      - id: changetitle_02
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - if: github.event.inputs.provenance_known == 'NO'
        id: changetitle_03
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            The issue appears to have come from a modified/customised instance.
            This item is therefore considered invalid and cannot be looked into.

            > [!IMPORTANT]
            > Issues found on modified/customised builds must be tested on official files/code.
            > Should they also appear on these sources, raise your issue based on such sources.
            > Additionally, debug logging and such should be obtained from the official sources.

            Thank you.

      # Remove Some Prior Labels if Present
      - if: github.event.inputs.provenance_known == 'NO'
        id: changetitle_04
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,No-Log,Queries,Noted,Incomplete,Tagged,Stale'

      # Add 'Invalid' Label
      - if: github.event.inputs.provenance_known == 'NO'
        id: changetitle_05
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Invalid'

      # Close Issue if Open
      - if: ${{ github.event.inputs.provenance_known == 'NO' && env.isclosed == 'false' }}
        id: changetitle_06
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          close-reason: 'completed'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}

      # Lock Issue if Unlocked
      - if: ${{ github.event.inputs.provenance_known == 'NO' && env.islocked == 'false' }}
        id: changetitle_07
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          issue-state: 'closed'

      # Update Issue Title - GitHub API
      - id: changetitle_08
        env:
          ENV_TOKEN: ${{ steps.app-token.outputs.token }}
          ENV_REPO: ${{ github.repository }}
          ENV_ISSUE_ID: ${{ github.event.inputs.item_id }}
          ENV_OUR_TITLE: ${{ github.event.inputs.new_title }}
          ENV_PROVENANCE_TAG: ${{ github.event.inputs.provenance_tag }}
          ENV_PROVENANCE_KNOWN: ${{ github.event.inputs.provenance_known }}
        shell: bash
        run: |
          # Set Title
          if [ "${ENV_PROVENANCE_KNOWN}" == 'YES' ]; then
            NewTitle="${ENV_OUR_TITLE}"
          else
            # Use default if ENV_PROVENANCE_TAG is blank
            TheTag="${ENV_PROVENANCE_TAG:-Exhibits Issues}"
            TheTag="$(echo "${TheTag}" | xargs)"
            if [ -z "${TheTag}" ]; then
              TheTag="Exhibits Issues"
            fi
            NewTitle="RefindPlus of Unknown Provenance: ${TheTag}"
          fi

          echo "Updating issue #${ENV_ISSUE_ID} with title: ${NewTitle}"
          curl -f -X PATCH \
            -H "Authorization: token ${ENV_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${ENV_REPO}/issues/${ENV_ISSUE_ID} \
            -d "{\"title\": \"${NewTitle}\"}" || { echo "Title Update Failed"; exit 1; }
