name: 'Issue Helper Resolve KnownIssue (Without Commit Ref)'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'Item ID'
        type: string
        required: true
      show_build_msg:
        description: 'Version Comment'
        type: choice
        options:
        - 'Yes'
        - 'No'
      more_info:
        description: 'More Info'
        type: string
      show_more_info:
        description: 'Show More Info Entry'
        type: choice
        options:
        - 'No'
        - 'Yes'
      type_more_info:
        description: 'More Info Type'
        type: choice
        options:
        - 'Note'
        - 'Caution'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  issue_resolve_knownissue1:
    name: Issue - Resolve - KnownIssue1
    runs-on: ubuntu-24.04

    steps:
      # Generate App Token - https://github.com/actions/create-github-app-token
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: issue-get-state
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const issueNumber = context.payload.inputs.item_id;
            const { data } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            const isClosed = data.state === 'closed' ? 'true' : 'false';

            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `isclosed=${isClosed}\n`);

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' }}
        id: part_2_1a
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.app-token.outputs.token }}
          releases-only: true

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Note' }}
        id: part_2_1b
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |-
            This item has been addressed for the next RefindPlus release.
            The current release version is **${{ steps.part_2_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

            > [!NOTE]
            > ${{ github.event.inputs.more_info }}

            Thank you for taking the time to report a problem with RefindPlus.

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Caution' }}
        id: part_2_1c
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been addressed for the next RefindPlus release.
            The current release version is **${{ steps.part_2_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

            > [!CAUTION]
            > ${{ github.event.inputs.more_info }}

            Thank you for taking the time to report a problem with RefindPlus.

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'No' }}
        id: part_2_1d
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been addressed for the next RefindPlus release.
            The current release version is **${{ steps.part_2_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

            Thank you for taking the time to report a problem with RefindPlus.

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Note' }}
        id: part_2_2a
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been addressed for the next RefindPlus release.

            > [!NOTE]
            > ${{ github.event.inputs.more_info }}

            Thank you for taking the time to report a problem with RefindPlus.

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Caution' }}
        id: part_2_2b
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been addressed for the next RefindPlus release.

            > [!CAUTION]
            > ${{ github.event.inputs.more_info }}

            Thank you for taking the time to report a problem with RefindPlus.

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'No' }}
        id: part_2_2c
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been addressed for the next RefindPlus release.

            Thank you for taking the time to report a problem with RefindPlus.

      - id: part_3_1
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Known-Issue,Resolved'

      - id: part_3_2
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,Queries,Parked,Prorogued,Unclear,Uncertain,Unresolved,Confirmed,Bug'

      - if: ${{ env.isclosed == 'false' }}
        id: part_4
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          close-reason: 'completed'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
