name: 'Issue Helper Resolve Other'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'Item ID'
        required: true
      show_buildmsg:
        type: choice
        description: 'Version Comment'
        options:
        - 'Yes'
        - 'No'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_resolve_other1:
    name: Issue - Resolve - Other1
    runs-on: ubuntu-20.04

    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}


  issue_resolve_other2:
    name: Issue - Resolve - Other2
    needs: [issue_resolve_other1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - if: ${{ github.event.inputs.show_buildmsg == 'Yes' }}
        id: part_1a
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          releases-only: true

      - if: ${{ github.event.inputs.show_buildmsg == 'Yes' }}
        id: part_1b
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            Current RefindPlus Release: ${{ steps.part_1a.outputs.tag }}.
            Refer to BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) to access functionality before next release.

      - if: ${{ github.event.inputs.show_buildmsg == 'No' }}
        id: part_2
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

  issue_resolve_other3:
    name: Issue - Resolve - Other3
    needs: [issue_resolve_other2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Resolved'

  issue_resolve_other4:
    name: Issue - Resolve - Other4
    needs: [issue_resolve_other3]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,Queries,Parked,Prorogued,Unclear,Uncertain,Unresolved'

  issue_resolve_other5:
    name: Issue - Resolve - Other5
    needs: [issue_resolve_other4]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          close-reason: 'completed'
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
