name: 'Issue Helper Duplicate'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'This Item ID'
        type: string
        required: true
      orig_id:
        description: 'Original Item ID'
        type: string
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items
  issue_duplicate1:
    name: Issue - Duplicate1
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.inputs.item_id }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: issueduplicate_03
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          ORIG_ID: ${{ github.event.inputs.orig_id }}
        run: |
          {
            echo "This item is a duplicate of one or more existing items"
            echo ""
            echo "Please refer to Item #${ORIG_ID}."
          } > comment-body.md
          gh issue comment "$ISSUE_NUMBER" --body-file comment-body.md

  issue_duplicate2:
    name: Issue - Duplicate2
    needs: [issue_duplicate1]
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.inputs.item_id }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: issueduplicate_04
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh issue edit "$ISSUE_NUMBER" --add-label 'Duplicate'

  issue_duplicate3:
    name: Issue - Duplicate3
    needs: [issue_duplicate2]
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.inputs.item_id }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: issueduplicate_05
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh issue edit "$ISSUE_NUMBER" --remove-label 'Triage,No-Log,Queries,Parked,Prorogued,Unclear,Uncertain'

  issue_duplicate4:
    name: Issue - Duplicate4
    needs: [issue_duplicate3]
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.inputs.item_id }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: issueduplicate_06
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh issue close "$ISSUE_NUMBER" --reason "completed"
