name: 'Issue Helper Resolve Other'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'Item ID'
        required: true
      show_build_msg:
        type: choice
        description: 'Version Comment'
        options:
        - 'Yes'
        - 'No'
      more_info:
        description: 'More Info'
      show_more_info:
        type: choice
        description: 'Show More Info Entry'
        options:
        - 'No'
        - 'Yes'
      type_more_info:
        type: choice
        description: 'More Info Type'
        options:
        - 'Note'
        - 'Caution'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_resolve_other1:
    name: Issue - Resolve - Other1
    runs-on: ubuntu-20.04

    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}


  issue_resolve_other2:
    name: Issue - Resolve - Other2
    needs: [issue_resolve_other1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - if: ${{ github.event.inputs.show_build_msg == 'Yes' }}
        id: part_1a
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          releases-only: true

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Note' }}
        id: part_1b
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            The current RefindPlus release is **${{ steps.part_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

            > [!NOTE]
            > ${{ github.event.inputs.more_info }}

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Caution' }}
        id: part_1c
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            The current RefindPlus release is **${{ steps.part_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

            > [!CAUTION]
            > ${{ github.event.inputs.more_info }}

      - if: ${{ github.event.inputs.show_build_msg == 'Yes' && github.event.inputs.show_more_info == 'No' }}
        id: part_1d
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            The current RefindPlus release is **${{ steps.part_1a.outputs.tag }}**.
            See [BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) for how to access functionality ahead of releases.

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Note' }}
        id: part_2a
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            > [!NOTE]
            > ${{ github.event.inputs.more_info }}

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'Yes' && github.event.inputs.type_more_info == 'Caution' }}
        id: part_2b
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            > [!CAUTION]
            > ${{ github.event.inputs.more_info }}

      - if: ${{ github.event.inputs.show_build_msg == 'No' && github.event.inputs.show_more_info == 'No' }}
        id: part_2c
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

  issue_resolve_other3:
    name: Issue - Resolve - Other3
    needs: [issue_resolve_other2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Resolved'

  issue_resolve_other4:
    name: Issue - Resolve - Other4
    needs: [issue_resolve_other3]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,Queries,Parked,Prorogued,Unclear,Uncertain,Unresolved'

  issue_resolve_other5:
    name: Issue - Resolve - Other5
    needs: [issue_resolve_other4]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          close-reason: 'completed'
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
