name: 'Issue Helper Resolve'

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: Issue Action
        options:
        - 'Issue - Resolve - Bug'
        - 'Issue - Resolve - Other'
      item_id:
        description: 'Item ID'
        required: true
      commmit_ref:
        description: 'Commit Ref'
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_resolve_bug1:
    name: Issue - Resolve - Bug1
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Resolve - Bug'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_resolve_bug2:
    name: Issue - Resolve - Bug2
    needs: [issue_resolve_bug1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item was addressed by Commit ${{ github.event.inputs.commmit_ref }}.

            Refer to [BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) to access the functionality ahead of the next release.

  issue_resolve_bug3:
    name: Issue - Resolve - Bug3
    needs: [issue_resolve_bug2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Bug,Resolved'

  issue_resolve_bug4:
    name: Issue - Resolve - Bug4
    needs: [issue_resolve_bug3]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,Queries,Parked,Prorogued,Unclear,Uncertain,Unresolved,Acknowledged,Known-Issue'

  issue_resolve_bug5:
    name: Issue - Resolve - Bug5
    needs: [issue_resolve_bug4]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          close-reason: 'completed'
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_resolve_other1:
    name: Issue - Resolve - Other1
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Resolve - Other'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}


  issue_resolve_other2:
    name: Issue - Resolve - Other2
    needs: [issue_resolve_other1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            This item has been resolved.

            Refer to [BUILDING.md](https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md) to access the functionality ahead of the next release.

  issue_resolve_other3:
    name: Issue - Resolve - Other3
    needs: [issue_resolve_other2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Resolved'

  issue_resolve_other4:
    name: Issue - Resolve - Other4
    needs: [issue_resolve_other3]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,Queries,Parked,Prorogued,Unclear,Uncertain,Unresolved'

  issue_resolve_other5:
    name: Issue - Resolve - Other5
    needs: [issue_resolve_other4]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          close-reason: 'completed'
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
