name: 'Issue Helper Assign'

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Issue Action'
        type: choice
        options:
        - 'Assignment - Self - Add'
        - 'Assignment - Self - Remove'
        default: 'Assignment - Self - Add'
      item_id:
        description: 'Item ID'
        type: string
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  add_assignees:
    name: Assignment - Self - Add
    runs-on: ubuntu-24.04

    if: github.event.inputs.operation == 'Assignment - Self - Add'
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          assignees: ${{ github.actor }}

  remove_assignees:
    name: Assignment - Self - Remove
    runs-on: ubuntu-24.04

    if: github.event.inputs.operation == 'Assignment - Self - Remove'
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-assignees'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          assignees: ${{ github.actor }}
