
name: 'Manage Runs'

on:
  workflow_dispatch:
  schedule:
    # Every 1st Day of Month at 01:01
    - cron: '1 1 1 * *'

jobs:

  # Prune Old Runs - https://github.com/Mattraks/delete-workflow-runs
  del_runs:
    name: Prune Runs
    runs-on: ubuntu-latest

    steps:
      - name: Generate App Token
        if: github.repository == 'RefindPlusRepo/RefindPlus'
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: App Token Prune
        if: github.repository == 'RefindPlusRepo/RefindPlus'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          retain_days: 42
          keep_minimum_runs: 0

      - name: Default Token Prune
        if: github.repository != 'RefindPlusRepo/RefindPlus'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 42
          keep_minimum_runs: 0
