name: Manage PR Close

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: manage-pr-close-${{ github.event.pull_request.number }}

jobs:
  handle-labels:
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Accepted: PR Merged
      - if: github.event.pull_request.merged == true
        id: add-labels-accepted
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr edit "$PR_NUMBER" --add-label 'Accepted'

      # Declined: Maintainer/Bot Closed Contributor PR
      - if: >-
          !github.event.pull_request.merged &&
          github.event.pull_request.user.login != github.actor &&
          (github.actor == 'refindplusrepo[bot]' || github.actor == 'dakanji')
        id: add-labels-declined
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr edit "$PR_NUMBER" --add-label 'Declined'

      # Withdrawn: PR Author Closed PR Themselves
      - if: >-
          !github.event.pull_request.merged &&
          github.event.pull_request.user.login == github.actor
        id: add-labels-withdrawn
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr edit "$PR_NUMBER" --add-label 'Withdrawn'

      - id: remove-labels
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr edit "$PR_NUMBER" --remove-label 'Triage,Queries,Pending,Prorogued'
